# Source: unocoins/templates/secrets.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: unocoins-secrets
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: gcpSecretsManager
  projectId: corded-imagery-343815
  data:
    - name: sa.json
      key: pluto-unocoins-secrets
      property: sa.json
      version: latest
    - name: BQ_PROJECT_ID
      key: pluto-unocoins-secrets
      property: BQ_PROJECT_ID
      version: latest
    - name: BQ_YF_DATASET_NAME
      key: pluto-unocoins-secrets
      property: BQ_YF_DATASET_NAME
      version: latest
    - name: BQ_IEX_DATASET_NAME
      key: pluto-unocoins-secrets
      property: BQ_IEX_DATASET_NAME
      version: latest
    - name: BQ_YF_HISTORICALS_TABLENAME
      key: pluto-unocoins-secrets
      property: BQ_YF_HISTORICALS_TABLENAME
      version: latest
    - name: BQ_SYMBOLMAP
      key: pluto-unocoins-secrets
      property: BQ_SYMBOLMAP
      version: latest
    - name: BQ_EXCHANGES_TABLE
      key: pluto-unocoins-secrets
      property: BQ_EXCHANGES_TABLE
      version: latest
    - name: BQ_IEX_SYMBOLS
      key: pluto-unocoins-secrets
      property: BQ_IEX_SYMBOLS
      version: latest
    - name: SYMBOLS_DB
      key: pluto-unocoins-secrets
      property: SYMBOLS_DB
      version: latest
    - name: EXCHANGES_DB
      key: pluto-unocoins-secrets
      property: EXCHANGES_DB
      version: latest
    - name: BQ_CRYPTO_DATASET_NAME
      key: pluto-unocoins-secrets
      property: BQ_CRYPTO_DATASET_NAME
      version: latest
    - name: BQ_CRYPTO_QUOTES
      key: pluto-unocoins-secrets
      property: BQ_CRYPTO_QUOTES
      version: latest
    - name: BQ_CRYPTO_SYMBOLS
      key: pluto-unocoins-secrets
      property: BQ_CRYPTO_SYMBOLS
      version: latest
    - name: EXCHANGES_API
      key: pluto-unocoins-secrets
      property: EXCHANGES_API
      version: latest
    - name: CRYPTO_API
      key: pluto-unocoins-secrets
      property: CRYPTO_API
      version: latest
    - name: CRYPTO_METADATA
      key: pluto-unocoins-secrets
      property: CRYPTO_METADATA
      version: latest
    - name: CRYPTO_PRICES
      key: pluto-unocoins-secrets
      property: CRYPTO_PRICES
      version: latest
    - name: IEX_INFO
      key: pluto-unocoins-secrets
      property: IEX_INFO
      version: latest
    - name: YF_INFO
      key: pluto-unocoins-secrets
      property: YF_INFO
      version: latest
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'unocoins'
    type: Opaque
