apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: binomy
    provider: github
    repository: stocks-ui
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: binomy-stocks-ui
  namespace: jx
spec:
  httpCloneURL: https://github.com/binomy/stocks-ui.git
  org: binomy
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: stocks-ui
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/binomy/stocks-ui
