filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
- name: dev
  url: https://chartmuseum.pluto.binomy.io
releases:
- chart: jxgh/jx-verify
  name: jx-verify
  namespace: jx-production
  values:
  - jx-values.yaml
- chart: dev/origins-cms
  version: 0.0.11
  name: origins-cms
  namespace: jx-production
  values:
  - jx-values.yaml
- chart: jxgh/acme
  version: 0.0.24
  condition: jxRequirementsIngressTLS.enabled
  name: acme-jx
  namespace: jx-production
  values:
  - jx-values.yaml
  - acme-values.yaml
templates: {}
renderedvalues: {}
