# Source: origins-cms/templates/secrets.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: origins-cms-secrets
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: gcpSecretsManager
  projectId: corded-imagery-343815
  data:
    - name: SESSION_SECRET
      key: pluto-origins-cms-secrets
      property: SESSION_SECRET
      version: latest
    - name: DATABASE_URL
      key: pluto-origins-cms-secrets
      property: DATABASE_URL
      version: latest
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'origins-cms'
    type: Opaque
