# Source: origins-cms/templates/secrets.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: origins-cms-db-url
  namespace: jx-staging
  annotations:
    secret.jenkins-x.io/replica: 'true'
    meta.helm.sh/release-name: 'origins-cms'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
    secret.jenkins-x.io/replica-source: 'true'
spec:
  backendType: gcpSecretsManager
  projectId: corded-imagery-343815
  data:
    - name: DATABASE_URL
      key: pluto-origins-cms-db-url
      property: DATABASE_URL
      version: latest
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'origins-helmfile-resources'
      labels:
        secret.jenkins-x.io/replica-source: 'true'
    type: Opaque
