# Source: unocoins/templates/secrets.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: unocoins-secrets
  namespace: jx-production
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: gcpSecretsManager
  projectId: corded-imagery-343815
  data:
    - name: sa.json
      key: pluto-unocoins-secrets
      property: sa.json
      version: latest
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'unocoins'
    type: Opaque
